//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itlize.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AvengersEntities : DbContext
    {
        public AvengersEntities()
            : base("name=AvengersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCategory> tblCategory { get; set; }
        public virtual DbSet<tblManufacturer> tblManufacturer { get; set; }
        public virtual DbSet<tblProduct> tblProduct { get; set; }
        public virtual DbSet<tblSubCategory> tblSubCategory { get; set; }
        public virtual DbSet<tblTechSpecFilter> tblTechSpecFilter { get; set; }
        public virtual DbSet<tblTypeFilter> tblTypeFilter { get; set; }
        public virtual DbSet<tblUser> tblUser { get; set; }
    }
}
